### ISSUE TITLE
下载打开还是英文

### ISSUE THREAD

**Issue by mummer98** [Nriver/trilium-translation#1]
![image](https://user-images.githubusercontent.com/77563657/121495585-50443e00-ca0c-11eb-89d5-2113d2d77dbd.png)
按照说明文档，直接打开。还是英文的啊
![image](https://user-images.githubusercontent.com/77563657/121495638-5f2af080-ca0c-11eb-896b-72258ab8002a.png)

**Comment by Nriver** [comment]
之前发布的时候执行脚本出了点问题, 我换了个环境重新打包了一下
https://github.com/Nriver/trilium-translation/releases

**Comment by Nriver** [comment]
问题解决咯 关issue
