### ISSUE TITLE
docker服务端不支持arm架构？

### ISSUE THREAD

**Issue by cklx0719** [Nriver/trilium-translation#10]
我在甲骨文云的A1服务器上，官方的原版docker是可以跑的，这个中文的服务端跑不了，提示
trilium-cn    | standard_init_linux.go:228: exec user process caused: exec format error
应该是不支持arm架构。

**Comment by Nriver** [comment]
我的系统默认amd64的镜像，等我看看怎么做跨平台架构的镜像

**Comment by Nriver** [comment]
我加了arm版本的镜像，但是我没有设备，麻烦试试能不能正常使用，地址还是原来的

**Comment by Nriver** [comment]
不知道怎么打出能用的arm镜像，希望有大神帮忙。

**Comment by attychen** [comment]
> 不知道怎么打出能用的arm镜像，希望有大神帮忙。

https://hub.docker.com/r/hlince/trilium    这个可以，我也是甲骨文 arm  希望大佬翻译一下

**Comment by jzf387897543** [comment]
希望能打包出ARM架构的

**Comment by SenLief** [comment]
trilium-cn-linux-x64-server 这个也要打包成arm64的吧，我看dockerfile依赖了这个文件。

**Comment by Nriver** [comment]
> trilium-cn-linux-x64-server 这个也要打包成arm64的吧，我看dockerfile依赖了这个文件。

汉化版是根据原版的Release文件修改的, 原版就没有arm64的包, 我也不知道怎么做

**Comment by sleepwood** [comment]
现在原版已经支持arm了 汉化还会更新arm版本么?

**Comment by Nriver** [comment]
> 现在原版已经支持arm了 汉化还会更新arm版本么?

现在原版的release并没有arm，汉化版也不会更新arm。

**Comment by CoderL98** [comment]
可以给一下打包时用的Dockerfile么 我想打arm64的镜像 但好像Dockerfile有问题 镜像一直运行不起来

**Comment by Nriver** [comment]
> 可以给一下打包时用的Dockerfile么 我想打arm64的镜像 但好像Dockerfile有问题 镜像一直运行不起来

到release里 trilium-linux-x64-server.zip 解压出来放dockerfile同目录

**Comment by CoderL98** [comment]
Max retries exceeded with url: /zadam/trilium/releases/download/v0.57.5/trilium-linux-x64-0.57.5.tar.xz (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff98b7c610>: Failed to establish a new connection: [Errno 111] Connection refused')))
我执行您的init初始化脚本报这个错误 请问这个需要怎么解决呀
我得环境为arm64 Deian 11 Python 3.9.2 pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)

**Comment by Nriver** [comment]
没配置代理
看下说明吧，代码里都有注释 https://github.com/Nriver/trilium-translation/blob/main/README_CN.md#翻译过程

**Comment by zhuhuashan** [comment]
docker 在搜索的时候不是有arm 架构的吗，但是我们运行[](url)
![macPic_2023-03-06 11 21 28](https://user-images.githubusercontent.com/13775331/223012344-99efe74f-e342-48df-b3e5-9c3359f7bbf5.png)

**Comment by Nriver** [comment]
> docker 在搜索的时候不是有arm 架构的吗，但是我们运行[](url)
> ![macPic_2023-03-06 11 21 28](https://user-images.githubusercontent.com/13775331/223012344-99efe74f-e342-48df-b3e5-9c3359f7bbf5.png)
> 

不是我发的呢。

**Comment by Nriver** [comment]
如果需要在Arm服务器上跑，可以直接用trilium原版的docker镜像。汉化版和原版数据是互通的。可以用汉化版的客户端和原版的服务端进行链接。

汉化版暂时不会有Arm镜像。

**Comment by fishandbread** [comment]
使用 GitHub Actions 自动构建

**Comment by fishandbread** [comment]
原版的可以docker部署到arm机器上，中文版的为什么部署了就运行不了呢？？？

**Comment by Nriver** [comment]
> 原版的可以docker部署到arm机器上，中文版的为什么部署了就运行不了呢？？？

上面已经回答过了 ¯\_(ツ)_/¯

等厉害的大神来解决吧，欢迎提供测试后可用的解决方案。

**Comment by Nriver** [comment]
经过各路大神的指导，汉化版的docker镜像已经支持arm环境了，欢迎来测试。
