### ISSUE TITLE
关于v0.63.5客户端在win11中无法运行的问题

### ISSUE THREAD

**Issue by cpxjaz** [Nriver/trilium-translation#100]
最近将服务器端更新到了[v0.63.5]版本，在本地操作系统为windows11的电脑上（之前安装过旧版本客户端但已删除）运行v0.63.5客户端无任何反应，尝试过管理员权限，但问题依旧。
而在另一台操作系统为windows10的电脑上（之前从未安装过客户端）运行客户端，可以正常打开界面
非常感谢您的回答

**Comment by Nriver** [comment]
cmd运行看报错

**Comment by cpxjaz** [comment]
> cmd运行看报错

非常感谢，问题是由于从过低版本直接升级至最新版导致，之前以为只有服务端需要按顺序升级就行，原来客户端也需要按顺序升级
