### ISSUE TITLE
trilium客户端如何更改服务端地址

### ISSUE THREAD

**Issue by meimingziyongle** [Nriver/trilium-translation#101]

**Comment by meimingziyongle** [comment]
windows版本的

**Comment by Nriver** [comment]
同步 设置里面可以修改。能同步的前提是客户端初始化就从服务端同步。如果你是新建的另一个数据库，需要删掉本地数据库重新同步。

**Comment by meimingziyongle** [comment]
> 同步 设置里面可以修改。能同步的前提是客户端初始化就从服务端同步。如果你是新建的另一个数据库，需要删掉本地数据库重新同步。

“trilium-data”这里的三个db文件吗

**Comment by Nriver** [comment]
最好整个文件夹都移走

**Comment by meimingziyongle** [comment]
> 最好整个文件夹都移走

感谢
