### ISSUE TITLE
关于字体的一个建议

### ISSUE THREAD

**Issue by junevin1** [Nriver/trilium-translation#102]
trilium的字体可以在css里定义，如果客户端有对应的字体自然没问题。可是没有对应的字体从服务器传过来的话每次打开都会需要好几秒才打开。
很影响体验，尤其是在ios端。我的想法是能不能在PWA的代码里加入字体缓存，这样就解决了trilium的字体问题。

**Comment by Nriver** [comment]
功能建议请去原版提issue，或者去trilium-next提issue
