### ISSUE TITLE
docker部署后，新建笔记需要F5刷新才能显示

### ISSUE THREAD

**Issue by justsonghua** [Nriver/trilium-translation#103]
如题，我通过Docker部署在Unraid上，并且使用Nginx进行了反向代理。但是遇到了新建笔记或者修改图标类的操作，都需要手动刷新才能在网页上显示操作后的内容。

请问大佬这是什么原因。

Nginx设置如下
<img width="366" alt="PixPin_20240606_145325" src="https://github.com/Nriver/trilium-translation/assets/41994375/00061b95-baa9-45d0-bdd1-58b1492d4fed">

**Comment by justsonghua** [comment]
现在又可以实时在网页上显示操作后的项目了，不清楚是什么原因。

**Comment by Nriver** [comment]
没有配置websocket就会这样
