### ISSUE TITLE
大佬请教个问题，最近研究api，关于通过接口获取内容时，图片提示: Logged in session not found

### ISSUE THREAD

**Issue by openapphub** [Nriver/trilium-translation#105]
客户端访问正常：
<img width="747" alt="image" src="https://github.com/user-attachments/assets/2be4f4fb-a1d8-4c16-afe0-904b562ad9be">

通过 `/notes/{noteId}/content` 接口获取到 img 标签节点 `<img style="aspect-ratio:1012/1185;" src="api/attachments/OfFAHS3RFFOC/image/8-8.jpg" alt="image.png" width="1012" height="1185">`。通过反向代理，将图片地址指向部署地址，同时添加请求头 `Authorization`，依旧提示 Logged in session not found。只有本地 dev 开发的时候，将代理指向本地 http://127.0.0.1:37840 才可以访问。

大佬知道如何处理吗

**Comment by Nriver** [comment]
Authorization是哪来的？
你这是缺少登录的cookie
