### ISSUE TITLE
翻译修正：Copy/clone应为复制/克隆

### ISSUE THREAD

**Issue by YiChuJun** [Nriver/trilium-translation#11]
嗨，有一个小问题，右键菜单里的**Copy/clone**翻译成**复制/克隆**会更精准一点，因为trilium**Copy/clone**里的**Copy**不是字面意义的**copy**而是一种引用，具体解释可以参考这个[克隆笔记](https://github.com/baddate/trilium/wiki/克隆笔记)。
> 我称这些为“clones”（克隆），但这有点误导性 - 没有原始和克隆的笔记 - 两个父类别中的笔记是相同的。

同样，**Clone to**建议翻译成**克隆到**:)

**Comment by Nriver** [comment]
谢谢指正，下次发布会更新

**Comment by Nriver** [comment]
已修复
