### ISSUE TITLE
linux docker桌面版是英文

### ISSUE THREAD

**Issue by bujue1** [Nriver/trilium-translation#115]
![CD7D2052-20F3-48b7-B8F7-28F1C03CBEDA](https://github.com/user-attachments/assets/ef9efd10-76bb-4099-8031-586a92e444af)
桌面版是英文，移动版是中文
能否告知一下应该如何解决么，有查看了常见问题，需要在Linux系统删除这个目录~/.config/Trilium Notes/ 
但是我找了并没有该目录。

**Comment by Nriver** [comment]
全盘搜Trilium试试, 你的系统可能把它放到别的地方了

**Comment by bujue1** [comment]
感谢你的回复，我也全盘搜索了找不到Trilium Notes，只有容器数据Trilium-data相关目录。

**Comment by Nriver** [comment]
等下, 你这个"桌面版"说的是桌面浏览器版, 不是指桌面客户端?
试试清空浏览器缓存

**Comment by bujue1** [comment]
感谢指正 
确实是浏览器缓存的问题 清理后网页桌面版就变成中文了 非常感谢
---- 回复的原邮件 ----
发件人Nate ***@***.***>发送日期2024年10月26日 09:41 ***@***.***> ***@***.***>,
***@***.***>主题Re: [Nriver/trilium-translation] linux docker桌面版是英文 (Issue #115)
等下, 你这个"桌面版"说的是桌面浏览器版, 不是指桌面客户端?
试试清空浏览器缓存
