### ISSUE TITLE
如何将笔记拖入到Excalidraw中？如何获取笔记的id链接，右键没有这个选项

### ISSUE THREAD

**Issue by xm-iam** [Nriver/trilium-translation#117]
![image](https://github.com/user-attachments/assets/84cc3b04-c367-4f95-b24b-116b6aec888b)
如何将笔记拖入到Excalidraw中？如何获取笔记的id链接，右键没有这个选项

**Comment by Nriver** [comment]
自己手动构造链接 `#root/笔记id`

**Comment by xm-iam** [comment]
但是如何获取笔记ID？

**Comment by Nriver** [comment]
上面一排按钮里的笔记信息里有

**Comment by xm-iam** [comment]
我在笔记信息中心找到了了ID，能不能在笔记右键中加入复制笔记链接的选项？

**Comment by Nriver** [comment]
去trilim next提feature request吧
