### ISSUE TITLE
使用nginx proxy manager反向代理管理器，点击左下角的收起/展开开关没有反应，点击之后，需要刷新网页才会变化

### ISSUE THREAD

**Issue by GloogTs** [Nriver/trilium-translation#119]
在nginx proxy manager 也配置了使用websocket，也按网上的教程在自定义位置配置了：
`proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $http_connection;
`
也试过，也不行。
`proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";`

![{450EDE37-1315-40ca-B1B6-665753279656}](https://github.com/user-attachments/assets/0a622322-4d5e-47cd-9639-66acc92e8735)
![{D4104559-00EB-4016-A958-7A3CB32B2098}](https://github.com/user-attachments/assets/2508a2ab-c472-4b0a-9d8a-903bfc5c380d)
![{36CE3E3F-0910-48cb-8C45-C9D8E1CD904D}](https://github.com/user-attachments/assets/d1fbda1c-993d-4253-b2f8-3b35c0bc9b9e)

**Comment by Nriver** [comment]
这是没配置好websocket的表现。 F12或者ctrl shift i 看控制台报错

**Comment by Nriver** [comment]
我没用过npm，不知道这个界面要怎么配置。得去看你的nginx配置文件是哪里配置错了，

**Comment by GloogTs** [comment]
搞定了，问题可以关闭了。
其实npm不需要在自定义位置或者高级里面增加任何代码，只要开启websocket支持就行。
之前主要犯了几个错误，导致wss和ws连不上。
1、在群晖自带的反向代理中代理了npm的端口
2、cloudflare中websocket支持没开启
3、npm没配置证书，也是因为错误1导致配不配证书都不行，反复试不出来

**Comment by Nriver** [comment]
感谢分享经验。以后有用户遇到类似的问题我可以让他们参考一下。
