### ISSUE TITLE
数据保存在哪儿?可以导入导出吗

### ISSUE THREAD

**Issue by dotkt** [Nriver/trilium-translation#13]

**Comment by Nriver** [comment]
readme里都有写
https://github.com/Nriver/trilium-translation/blob/main/README_CN.md#笔记数据库在哪?

在左侧的树上点右键就能导入导出

**Comment by dotkt** [comment]
谢谢,不好意思打扰了
________________________________
发件人: Nriver ***@***.***>
发送时间: 2022年4月4日 18:38
收件人: Nriver/trilium-translation ***@***.***>
抄送: dotkt ***@***.***>; Author ***@***.***>
主题: Re: [Nriver/trilium-translation] 数据保存在哪儿?可以导入导出吗 (Issue #13)


readme里都有写
https://github.com/Nriver/trilium-translation/blob/main/README_CN.md#笔记数据库在哪<https://github.com/Nriver/trilium-translation/blob/main/README_CN.md#%E7%AC%94%E8%AE%B0%E6%95%B0%E6%8D%AE%E5%BA%93%E5%9C%A8%E5%93%AA>?

在左侧的树上点右键就能导入导出

―
