### ISSUE TITLE
Docker服务端中文版本和Windows客户端中文版本不一致

### ISSUE THREAD

**Issue by muxinxy** [Nriver/trilium-translation#16]
Windows客户端中文版本
![image](https://user-images.githubusercontent.com/32673109/165059413-8e975c7f-3ac0-490f-b95d-5f0dfa961f77.png)
Docker服务端中文版本
![image](https://user-images.githubusercontent.com/32673109/165059597-b27ecfd3-105d-43de-9b78-0d5affcb12f1.png)

**Comment by Nriver** [comment]
请看 #14

**Comment by muxinxy** [comment]
谢谢，确实是因为用了阿里云的镜像加速
