### ISSUE TITLE
docker 应用版本:0.51.2 ,启动出现错误

### ISSUE THREAD

**Issue by Mn-Simple** [Nriver/trilium-translation#18]
./node/bin/node[6]: ../src/node_platform.cc:61:std::unique_ptr node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb09980 node::Abort() [./node/bin/node]
 2: 0xb099fe  [./node/bin/node]
 3: 0xb78f9e  [./node/bin/node]
 4: 0xb79066 node::NodePlatform::NodePlatform(int, v8::TracingController*) [./node/bin/node]
 5: 0xaccf49 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [./node/bin/node]
 6: 0xacd1f9 node::Start(int, char**) [./node/bin/node]
 7: 0x7fe215850d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7fe215850e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xa4076c  [./node/bin/node]
Aborted (core dumped)

**Comment by Nriver** [comment]
你是啥系统，我在Manjaro上跑没有问题。

**Comment by Mn-Simple** [comment]
Debian10 5.10内核  Docker3.6 
使用下面docker-compose.yml  安装,同文件夹下的 trilium-data目录是空的
version: '3'
services:
  trilium-cn:
    image: nriver/trilium-cn
    restart: always
    ports:
      - "8080:8080"
    volumes:
      # 把同文件夹下的 trilium-data 目录映射到容器内
      - ./trilium-data:/root/trilium-data
    environment:
      # 环境变量表示容器内笔记数据的存储路径
      - TRILIUM_DATA_DIR=/root/trilium-data

**Comment by Nriver** [comment]
这里有个跟你的报错几乎一样的问题https://laracasts.com/discuss/channels/servers/npm-run-dev-is-showing-a-weird-error-on-shared-hosting

根据他的说法可能是你的服务器被限制了，不能同时运行太多进程

**Comment by Mn-Simple** [comment]
另类解决方法,十分无奈╭(╯^╰)╮
1.安装官方docker源 zadam/trilium  版本0.51.2 成功 (相同配置下)
2. 下载作者已汉化桌面软件对应版本0.51.2  
缺点是直接浏览器请求web ,是英文的.但桌面端还是有汉化的.

**Comment by Nriver** [comment]
我打包的docker镜像用的是ubuntu的底包，官方的是alpine，可能是ubuntu要多消耗一些资源吧

**Comment by Mn-Simple** [comment]
0.51.2 之前的版本我用的也是 nriver/trilium-cn 的源,都没有此类问题,算了,能用就行,感谢作者的汉化 .    d=====(￣▽￣*)b

**Comment by Totobo** [comment]
这个我用最新的镜像也有一样的报错。
操作系统centos 7 ，内核版本5.4.3-1.el7.elrepo.x86_64

**Comment by Totobo** [comment]
> 这个我用最新的镜像也有一样的报错。 操作系统centos 7 ，内核版本5.4.3-1.el7.elrepo.x86_64

哈哈，抱歉。
我的问题，升级了docker-ce版本之后解决了，应该是我docker版本太旧导致的。

**Comment by Nriver** [comment]
好的，感谢分享经验
