### ISSUE TITLE
发现一处bug

### ISSUE THREAD

**Issue by gzxiexl** [Nriver/trilium-translation#20]
单元格属性-将单元格文本对齐到中间
这个设置貌似是无效的

**Comment by Nriver** [comment]
确实有问题，我下了一个原版的也是无效的。而CKEditor这个功能是没问题的，应该是trilium原版的bug了。你可以到原作者那里提个issue试试， https://github.com/zadam/trilium/issues

**Comment by gzxiexl** [comment]
已经去反馈了

**Comment by Nriver** [comment]
ok
