### ISSUE TITLE
用webclipper保存后，所有文件内容全部显示保存的文件了

### ISSUE THREAD

**Issue by caoliang12121** [Nriver/trilium-translation#21]
用webclipper保存后，所有文件内容全部显示保存的文件了。

![image](https://user-images.githubusercontent.com/24539953/173170734-7cd6af51-29dd-4cc9-8aae-6067b5985771.png)
![image](https://user-images.githubusercontent.com/24539953/173170743-9b4a53c9-bd94-4a93-94b6-818ef31f4797.png)
![image](https://user-images.githubusercontent.com/24539953/173170806-07d4dac5-5797-42ce-bed4-76cc0380b5e4.png)

**Comment by Nriver** [comment]
没看懂，是什么问题？

**Comment by Nriver** [comment]
哦，你是说右边的显示有问题？我自己测了一下是正常的。
你可以把你的运行环境，客户端版本等信息总结一下，给作者发个issue问下 https://github.com/zadam/trilium-web-clipper
