### ISSUE TITLE
这个有Docker和安卓应用吗

### ISSUE THREAD

**Issue by ghostxiu** [Nriver/trilium-translation#22]
想在docker做服务端，安卓做客户端

**Comment by Nriver** [comment]
有服务端的docker镜像，参考说明 https://github.com/Nriver/trilium-translation/blob/main/README_CN.md#%E5%9C%A8docker%E9%87%8C%E8%BF%90%E8%A1%8C%E6%9C%8D%E5%8A%A1%E7%AB%AF

目前没有移动端app，可以直接通过手机浏览器访问服务端，有适配移动端的页面。

**Comment by ghostxiu** [comment]
你好！您的邮件已收到，处理成功后会与您联系。修ghostxiu

**Comment by ghostxiu** [comment]
你好！您的邮件已收到，处理成功后会与您联系。修ghostxiu
