### ISSUE TITLE
请教一个关于用户密码的问题

### ISSUE THREAD

**Issue by ghostxiu** [Nriver/trilium-translation#24]
之前好像有版本是支持多用户的，现在好像只能单用户了
还有问一下忘记密码怎么恢复

**Comment by Nriver** [comment]
并没有多用户版本。那个说要做多用户的开发者只是说了一下，并没有开发。而且现在trilium以及把用户名都去掉了，不会有多用户版本了。

忘记密码可以参考官方wiki修改密码 https://github.com/zadam/trilium/wiki/Troubleshooting#forgotten-usernamepassword

只是
