### ISSUE TITLE
如何管理图片

### ISSUE THREAD

**Issue by maple185** [Nriver/trilium-translation#25]
感谢大佬提供的中文版本。
我的环境是Ubuntu 22.04 LTS x86_64(Py3.7.8)　，使用了宝塔和docker架设了trilium中文版。我在使用trilium的时候上传了一些图片，我现在不想要这些图片了，我该如何去删除？直接删除相关笔记的话，是否可以同时删除笔记里的图片和附件？谢谢了

**Comment by Nriver** [comment]
直接删除笔记就行了, 笔记里的图片和附件其实是它的子笔记, 删掉笔记它们也会一起被删掉.
删除的时候会有提示告诉你还有哪些笔记会一起被删掉.

**Comment by maple185** [comment]
> 直接删除笔记就行了, 笔记里的图片和附件其实是它的子笔记, 删掉笔记它们也会一起被删掉. 删除的时候会有提示告诉你还有哪些笔记会一起被删掉.

感谢
