### ISSUE TITLE
中文文档

### ISSUE THREAD

**Issue by xiakong24** [Nriver/trilium-translation#3]
# 请问下汉化部分包括自带文档吗？
看示例图片自带文档已经汉化，但两个windows版本打开后的文档均为英文文档，删除了数据库进行初始化后默认文档仍旧为英文，是bug还是文档未汉化？

**Comment by Nriver** [comment]
自带的文档是有做汉化的，还没有发布。原来的英文示例我觉得有点乱，给它分了个类，做了一点修改。另外还加了一些我觉得有用的东西。周末我找个时间整理一下再发出来。

![ksnip_20210713-171259](https://user-images.githubusercontent.com/6752679/125425985-648f1885-d330-4e1a-8736-59d50f7bd612.png)

![ksnip_20210713-171358](https://user-images.githubusercontent.com/6752679/125426054-324557eb-2378-40bb-a3df-e2a698710d94.png)

![ksnip_20210713-171734](https://user-images.githubusercontent.com/6752679/125426192-fc4ec6a1-acf3-466f-9309-a657c75a5f47.png)

**Comment by xiakong24** [comment]
OK, 多谢！静候佳音。另多问一句，有没有电报群或者微信QQ交流群之类的，可以找到组织学习交流，如果没有，可以考虑欢迎建一个？有的话可直接回复或私邮 hl741596374123@126.com 多谢！

**Comment by Nriver** [comment]
建了一个qq群

Trilium Notes 交流群 686232370

![image](https://user-images.githubusercontent.com/6752679/125550117-ec2a118c-8628-46e4-99f4-7f7e12ba7ba6.png)

**Comment by uliuyt** [comment]
支持支持👍

**Comment by Nriver** [comment]
https://github.com/Nriver/trilium-translation/releases/tag/20210813

把内置的文档汉化加进来了，不过我做了些修改，删掉了一些我认为用处不大的内容。比如Trilium自带有TODO，所以我把不太好用的任务管理删了。另外增加了一些实用的示例，比如自定义api接口等。

原版的示例没有仔细分类，有些内容又在英文wiki上，我第一次看觉得一头雾水。所以我修改了示例文档的笔记结构，给不同功能的笔记进行分类。

你可以单独下载这个[导出的示例笔记zip文件](https://github.com/Nriver/trilium-translation/blob/main/demo-cn.zip)导入到你的笔记里。

**Comment by iaplxe** [comment]
非常感谢作者  这个笔记很好用   但是对我们这些英文不好的人  确实不友好

**Comment by Nriver** [comment]
最近群聊一直有新用户加入，之前的群已经满员了。我已经新建了Telegram群和QQ群。二维码已经放在说明里，请优先加入Telegram群，谢谢您的支持！请查看项目的中文说明：https://github.com/Nriver/trilium-translation/blob/main/README_CN.md
