### ISSUE TITLE
美人鱼图渲染延迟

### ISSUE THREAD

**Issue by Q78KG** [Nriver/trilium-translation#30]
美人鱼图代码输入后有很长的渲染延迟

**Comment by Nriver** [comment]
延迟是什么样的？我这里是实时渲染的

**Comment by Q78KG** [comment]
呃，就是你在输入的时候，图案会消失，然后等一会之后软件会刷新，然后才会出现图案了。或者点击其他笔记再回来也可以。关键在于这个刷新的等待时间非常长。

**Comment by Q78KG** [comment]
大概一分多钟的样子，不知道和cpu或者显卡又没有关系

**Comment by Nriver** [comment]
一分钟有点夸张了。要不找台性能高一点的电脑试试？要是还是慢，去问下原作者zadam，看看他有没有什么办法。

**Comment by Q78KG** [comment]
我的电脑性能已经很好了，锐龙R7+RTX3060Laptop

**Comment by Q78KG** [comment]
服务端和客户端都有这问题，网页也会这样

**Comment by Q78KG** [comment]
也许是trilium歧视AMD(

**Comment by Q78KG** [comment]
我去问一下他看看
