### ISSUE TITLE
你们的代码块有高亮吗

### ISSUE THREAD

**Issue by PowerDi** [Nriver/trilium-translation#31]
看到宣传图里是有颜色高亮的，Mac版本发现用所有的主题，在代码块里不管什么编程语言都是没有高亮的是什么原因呢？

另外想咨询下: 一些markdown语法可以用 ```c++直接指定编程语言，在trilium里应该如何直接键盘指定呢

**Comment by Nriver** [comment]
Trilium内置的只有`代码笔记 `才有高亮。

社区有大神通过自定义的组件给`文字笔记`的代码块也加上高亮, 使用组件后，在编辑块里面选择语言就会有高亮。

组件来自这里 https://github.com/zadam/trilium/discussions/2822
配置过程有点复杂，不过我整理好了  [SyntaxHighlightWidget 代码高亮组件.zip](https://github.com/Nriver/trilium-translation/files/9856605/SyntaxHighlightWidget.zip)，你可以试试在文件树右键导入这个笔记，重启trilium应该就能看到高亮

**Comment by Nriver** [comment]
请注意, 组件里面是有在前端运行的代码的, 所以导入的时候要把 “安全导入” 去掉, 不然代码不会生效. 这个是Trilium的安全机制, 导入的时候默认不让代码可以运行, 对可以信任的代码, 要手动关闭 “安全导入”.
