### ISSUE TITLE
0.56.1 选择内容无法通过鼠标点击的方式插入内部链接，只能通过快捷键插入的问题

### ISSUE THREAD

**Issue by nvcutrb** [Nriver/trilium-translation#32]
![image](https://user-images.githubusercontent.com/73949891/197977832-7d17fa0a-513c-434c-b4d8-a261bdd6b3a0.png)

**Comment by Nriver** [comment]
这个问题已经在原版里反馈过了 https://github.com/zadam/trilium/issues/3236

先暂时用快捷键吧，等作者修复。

**Comment by Nriver** [comment]
最新版已经修复
