### ISSUE TITLE
如何修改Trilium Notes和trilium data的位置

### ISSUE THREAD

**Issue by swenqing** [Nriver/trilium-translation#34]
![image](https://user-images.githubusercontent.com/37140550/199664536-f02bb246-bf45-4074-aa14-fc2d1eba8855.png)
下载了trilium，然后点击trilium.exe文件就在C盘出现了这些，请问这是笔记本地保存默认位置吗？如何修改到指定的D盘或者其他文件夹

**Comment by Nriver** [comment]
https://github.com/Nriver/trilium-translation/blob/main/README_CN.md#如何修改数据库位置

**Comment by swenqing** [comment]
> [https://github.com/Nriver/trilium-translation/blob/main/README_CN.md#如何修改数据库位置](https://github.com/Nriver/trilium-translation/blob/main/README_CN.md#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9%E6%95%B0%E6%8D%AE%E5%BA%93%E4%BD%8D%E7%BD%AE)

感谢，但是链接上描述很少，是剪切文件夹吗？软件设置内我也没有看到具体的更改数据库的按钮

**Comment by Nriver** [comment]
就是编辑一下那个`trilium-portable.bat`文件，把`TRILIUM_DATA_DIR`换成你想要的文件夹，然后用这个bat文件启动就行。

**Comment by AlicKei** [comment]
现在可以通过改系统变量
![image](https://github.com/Nriver/trilium-translation/assets/89149900/a5bf268b-2c71-42a2-982a-14dc8215391a)

**Comment by adapter-su** [comment]
Trilium Notes目录位置还是落到C:\User\当前用户\AppData下去了

**Comment by NiKlaus-K** [comment]
> 现在可以通过改系统变量 ![image](https://private-user-images.githubusercontent.com/89149900/293832199-a5bf268b-2c71-42a2-982a-14dc8215391a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDU5OTMsIm5iZiI6MTcxMTAwNTY5MywicGF0aCI6Ii84OTE0OTkwMC8yOTM4MzIxOTktYTViZjI2OGItMmM3MS00MmEyLTk4MmEtMTRkYzgyMTUzOTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA3MjEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMDk5NzNhNGFkYTY2NGYzODM4ODNkMDc4ZTEwNTgyZWUzZTY1MTgxYjI1MzdlY2NhNThlZjljNTVlNDExYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5xd4ecv1TFJ8AxtM5mtxiWwOf4BCdoBKUJJkJf0ImmE)

可行

**Comment by baileichao** [comment]
> Trilium Notes目录位置还是落到C:\User\当前用户\AppData下去了

一样的问题，哈哈，不知道怎样解决。
