### ISSUE TITLE
【问题】关于当前笔记显示其他笔记内容的问题

### ISSUE THREAD

**Issue by nvcutrb** [Nriver/trilium-translation#35]
那个text类型的笔记是跟着0.56.1版本升级到0.56.2的。（个人电脑创建的笔记，跟着软件一同升级的数据，0.56.2）
那个book类型的笔记是在其他电脑上用旧版本0.56.1软件创建的，而且是以导入的方式导入到个人电脑中的。（其他电脑创建的笔记，软件并没有升级，还是0.56.1）

我点击第一个笔记（text），显示的内容是正常的，点击下一个笔记，这个笔记类型是书（book），也很正常，但是问题来了，当点击前一个笔记（text）时，内容却不是第一个笔记（text）的内容，而是另一个笔记书（book）的内容，这就很奇怪了？
而且我还测试了上一级目录，发现内容都是book笔记的内容。
这个bug影响非常严重

**Comment by nvcutrb** [comment]
旧版本的数据导入到新版本的数据，影响笔记使用，导致内容无法切换成其他内容

**Comment by Nriver** [comment]
我以前也遇到过在某个笔记卡住了的情况，但是刷新一下就好了，没找到复现的方法，就没去提issue。
你可以到作者那里去提个issue问问，最好把那个book笔记也带上请他看看是什么问题。

**Comment by nvcutrb** [comment]
我已经提交问题了，等待解决

**Comment by Nriver** [comment]
这个是翻译错了，我改一下。实际应该是检查通过了，没有问题。

**Comment by Nriver** [comment]
关联issue https://github.com/zadam/trilium/issues/3305
