### ISSUE TITLE
v.56.2存在文章编目问题

### ISSUE THREAD

**Issue by wins-feng** [Nriver/trilium-translation#36]
我是从v0.51.1版本升级到v0.56.2，在编辑文章目录时，无论是用手动快捷方式（##），还是功能选择标题方式，都无法正常显示目录。存在如下bug：
1、有时会在设置3个标题以上时会自动显示目录，多数时候设置再多的标题也不会显示目录；
2、在修改目录级别时存在错乱的问题，如：目录级别不正确；

**Comment by Nriver** [comment]
默认是总计5个标题的时候会出现目录，可以在 选项-文字笔记-目录 设置里面修改，改成0只要有标题就会出现目录。

级别可以自己设置就在左边那个弹出的符号里面。
