### ISSUE TITLE
客户端 连接服务端问题

### ISSUE THREAD

**Issue by zhenzhenfish** [Nriver/trilium-translation#39]
你好  服务端只能有一个， 我客户端已连接上测试用的服务端 ，想切回到正常使用的服务端 怎么操作？  我试着把客户端删掉重新安装，打开还是连接测试用的服务端  这个该怎么处理？

**Comment by Nriver** [comment]
把本地的数据库移走或者删掉，然后重新初始化。

https://github.com/Nriver/trilium-translation/blob/main/README_CN.md#%E7%AC%94%E8%AE%B0%E6%95%B0%E6%8D%AE%E5%BA%93%E5%9C%A8%E5%93%AA
