### ISSUE TITLE
白屏

### ISSUE THREAD

**Issue by OrSamling** [Nriver/trilium-translation#4]
打开白花花一片，什么都没有
![tR07bqCmx3](https://user-images.githubusercontent.com/36894410/128337881-6cf4c16a-4a6b-49e9-a33b-a6d3283b8176.png)

**Comment by Nriver** [comment]
我试了4天前发布的 windows11 22000.120 可以运行Trilium Notes，你可能刚好是5天前的版本。。。

**Comment by OrSamling** [comment]
不能实现替换文件实现功能吗，还有就是他的语言文件夹下有为什么不能用

>
![explorer_m6aYp78zos](https://user-images.githubusercontent.com/36894410/129038866-0ebcf882-3d92-4059-9e58-c937de73bd7f.png)

**Comment by OrSamling** [comment]
好的，谢谢解惑
