### ISSUE TITLE
如何备份本地数据？

### ISSUE THREAD

**Issue by star2k** [Nriver/trilium-translation#40]
如何备份本地数据？C:\Users\Administrator\AppData\Roaming，好似有2个文件夹，是该软件的数据么，有没有办法指定到某一路径下？

**Comment by Nriver** [comment]
请参考

https://github.com/Nriver/trilium-translation/blob/main/README_CN.md#笔记数据库在哪

https://github.com/Nriver/trilium-translation/blob/main/README_CN.md#如何修改数据库位置

**Comment by star2k** [comment]
docker部署，只有docker-compose.yml模式么，普通的docker 单机容器代码有么？

**Comment by Nriver** [comment]
就用docker-compose吧，不容易出错
