### ISSUE TITLE
从其他本地笔记复制粘贴来迁移内容，或者通过导入MD文档，图片无法迁移过来？

### ISSUE THREAD

**Issue by star2k** [Nriver/trilium-translation#41]
从其他本地笔记复制粘贴来迁移内容，或者通过其他软件导出后，在trilium导入MD文档，会发现：图片全部丢失，无法迁移过来？求助解决方案！

**Comment by Nriver** [comment]
试试我写的这个程序来导入Markdwon文档，可以处理图片。
https://github.com/Nriver/trilium-py#advanced-usage-upload-markdown-files
