### ISSUE TITLE
请求添加scoop下载方式

### ISSUE THREAD

**Issue by themql** [Nriver/trilium-translation#43]
[scoop](https://github.com/ScoopInstaller/Scoop)是Windows下的一个命令行下载器

在scoop的extra bucket(软件仓库)中已有对zadam/trilium的支持，请问将来此仓库是否也能提供此下载方式

**Comment by Nriver** [comment]
可以，等我先研究一下这个scoop。

**Comment by themql** [comment]
感谢🙏

我搜索时发现其实有个人bucket里有Nriver/trilium-translation

https://scoop.sh/#/apps?q=trilium&s=0&d=1&o=false

希望对您有帮助

**Comment by Nriver** [comment]
试了一下Scoop，挺好用的，可惜官方仓库说只让放英文软件，我自己弄了一个源，以后会在这个源更新

添加源
```
scoop bucket add Scoop-Nriver https://github.com/nriver/Scoop-Nriver
```

安装 Trilium Notes 中文版
```
scoop install trilium-cn
```

**Comment by themql** [comment]
感谢🙏
