### ISSUE TITLE
可以添加开源字体 霞鹜文楷 么?

### ISSUE THREAD

**Issue by Dev-Wiki** [Nriver/trilium-translation#44]
字体链接: https://github.com/lxgw/LxgwWenkaiGB-Fusion

**Comment by Nriver** [comment]
我看了一下源码，没有可以直接加字体的地方。作者的说法是字体是主题的一部分，需要自己改字体可以参考自带的 `Steel Blue` 主题。Trilium的字体是woff2格式的，我看了一下你给的那个字体是ttf的，可能需要转换一下才能使用。

**Comment by Dev-Wiki** [comment]
已经暂时弃坑了, 更新以后 md写的, 复制出来粘贴到别的 md 笔记软件不认了...

**Comment by Nriver** [comment]
每个软件都可以有自己的markdown标准，有格式不兼容的问题很正常。

不过trilium更多侧重于所见即所得的编辑，对markdown的支持比较弱。

你用markdown比较多的话我推荐你使用vnote，也是开源的，我之前用了好几年。

**Comment by Dev-Wiki** [comment]
> 每个软件都可以有自己的markdown标准，有格式不兼容的问题很正常。
> 
> 不过trilium更多侧重于所见即所得的编辑，对markdown的支持比较弱。
> 
> 你用markdown比较多的话我推荐你使用vnote，也是开源的，我之前用了好几年。

主要是更新以后 富文本复制过去 格式也变了, 之前的老版本是可以的, 现在数据库 重构以后 不能降级...

**Comment by themql** [comment]
> 字体链接: https://github.com/lxgw/LxgwWenkaiGB-Fusion

https://chawyehsu.github.io/lxgw-wenkai-webfont/

三个样式里选一个复制到主题css里，然后把原字体Raleway全改为LXGW WenKai就行了

我成功了，霞鹜文楷确实漂亮

**Comment by gzxiexl** [comment]
> > 字体链接: https://github.com/lxgw/LxgwWenkaiGB-Fusion
> 
> https://chawyehsu.github.io/lxgw-wenkai-webfont/
> 
> 三个样式里选一个复制到主题css里，然后把原字体Raleway全改为LXGW WenKai就行了
> 
> 我成功了，霞鹜文楷确实漂亮

能否分享下主题

**Comment by themql** [comment]
> > > 字体链接: https://github.com/lxgw/LxgwWenkaiGB-Fusion
> > 
> > 
> > https://chawyehsu.github.io/lxgw-wenkai-webfont/
> > 三个样式里选一个复制到主题css里，然后把原字体Raleway全改为LXGW WenKai就行了
> > 我成功了，霞鹜文楷确实漂亮
> 
> 能否分享下主题

https://gist.github.com/themql/0e5116dbd249dc33e5e5fdd0c225a49c

基于原来Steel Blue主题改的

**Comment by gzxiexl** [comment]
> > > > 字体链接: https://github.com/lxgw/LxgwWenkaiGB-Fusion
> > > 
> > > 
> > > https://chawyehsu.github.io/lxgw-wenkai-webfont/
> > > 三个样式里选一个复制到主题css里，然后把原字体Raleway全改为LXGW WenKai就行了
> > > 我成功了，霞鹜文楷确实漂亮
> > 
> > 
> > 能否分享下主题
> 
> https://gist.github.com/themql/0e5116dbd249dc33e5e5fdd0c225a49c
> 
> 基于原来Steel Blue主题改的

还要把字体导入到主题吧？ 我照着设置 没有效果呀
