### ISSUE TITLE
archlinux的AUR脚本无法通过校验有效性通过

### ISSUE THREAD

**Issue by abolast** [Nriver/trilium-translation#49]
原因：第二次通过yay助手的时候之前下载的文件存在导致并没有重新获取下载
解决: PKGBUILD文件中source字段增加一个参数
source=("$pkgname-$pkgver.zip::https://github.com/Nriver/trilium-translation/releases/download/v$pkgver/trilium-cn-linux-x64.zip")
影响：这样会导致下载的文件名称改变，增加了版本号，也就不会因为文件名重复出现 “错误： 一个或多个文件没有通过有效性检查！”
结果：无报错成功安装升级

**Comment by Nriver** [comment]
感谢你提供了解决办法！我已经把PKGBUILD文件更新了。
我之前以为是本地环境有问题，每次会先用 `yay -Sc` 清理缓存之后再去更新，现在帮我解决了个大麻烦，十分感谢。
