### ISSUE TITLE
docker 提示名字不允许 yml 文件 需要调整下

### ISSUE THREAD

**Issue by zhuhuashan** [Nriver/trilium-translation#51]
evan@192 我的个人文档 % docker-compose -f docker-compose.yml up -d 
[+] Running 0/0
 ⠋ Container -trilium-cn-1  Creating                                                                                                                                                                                                      0.0s
Error response from daemon: Invalid container name (-trilium-cn-1), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

**Comment by Nriver** [comment]
你改了yml文件内容，名字改错了，前面多了一个减号

**Comment by zhuhuashan** [comment]
嗯，提示能看懂，我自己调整一下也就 能跑了
