### ISSUE TITLE
请教：一个Client端如何添加多个服务端；或者windows下如何设置两个client端分离，去分别连接服务端

### ISSUE THREAD

**Issue by BLOSEregedit** [Nriver/trilium-translation#55]
大佬，我想请教下，一台windows电脑，如何去连接两个不同的服务端？我在NAS上用docker建立了两个服务端分别进行笔记的记录，但电脑就只有一台，

**Comment by Nriver** [comment]
复制两份客户端，修改trilium-portable.bat，设置运行端口，比如
```
SET TRILIUM_PORT=37740
```
每个客户端设置的端口运行，可以同时启动多个客户端。

portable模式下的数据就在bat文件同目录下。

**Comment by BLOSEregedit** [comment]
非常感谢，已经通过这个方法解决了
