### ISSUE TITLE
docker启动报错...

### ISSUE THREAD

**Issue by 5dprince** [Nriver/trilium-translation#57]
./node/bin/node[6]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.

1: 0xb08f10 node::Abort() [./node/bin/node]
2: 0xb08f8e [./node/bin/node]
3: 0xb7515e [./node/bin/node]
4: 0xb75226 node::NodePlatform::NodePlatform(int, v8::TracingController*) [./node/bin/node]
5: 0xacbf74 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [./node/bin/node]
6: 0xaccb59 node::Start(int, char**) [./node/bin/node]
7: 0x14ad719ead90 [/lib/x86_64-linux-gnu/libc.so.6]
8: 0x14ad719eae40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
9: 0xa408ec [./node/bin/node]
Aborted

**Comment by Nriver** [comment]
你可以尝试升级一下docker，我用的是23版本的。之前有群友也说启动不了，是因为docker太旧了，升级到新版就可以了。

**Comment by Nriver** [comment]
没有反馈，先关了
