### ISSUE TITLE
代码高亮

### ISSUE THREAD

**Issue by zhaiyujin** [Nriver/trilium-translation#59]
在读模式下，高亮没有效果，只有在编辑模式下才有高亮
![image](https://github.com/Nriver/trilium-translation/assets/22185888/559c237f-1f8d-430a-8cde-bd54a58c2553)

**Comment by Nriver** [comment]
插件的问题去插件作者那里提issue吧 https://github.com/antoniotejada/Trilium-SyntaxHighlightWidget
