### ISSUE TITLE
是否可以改善一下有序列表的结构

### ISSUE THREAD

**Issue by Suceru** [Nriver/trilium-translation#60]
软件中创建一片笔记，然后创建有序列表后，两列表中间有空行无法完成自动连排
例如：
1、xxxxx【插入行中的图片-特大】
2、xxxxxx【插入行中的图片-特大】
改成图片单独成行后，取消序号就变成了多个1、：
1、xxxxx
【插入行中的图片-特大】
1、xxxxxx
【插入行中的图片-特大】
1、xxxxxxx
留了空行就出现无自动连排
1、xxxxx

1、xxxxxx
2、xxxxxxx

同时还有有序列表回车后自动添加序号没问题，但是按退格键后，直接删掉回车和序号了，而不是保留回车，删除序号
![image](https://github.com/Nriver/trilium-translation/assets/20983345/011160bb-2d64-48e3-848b-0594cafd1fae)

**Comment by Nriver** [comment]
修改起始数字
![ksnip_20230519-105655](https://github.com/Nriver/trilium-translation/assets/6752679/e61e0f9b-8564-4526-aae2-a2e8b417cc41)

**Comment by Suceru** [comment]
> 修改起始数字 ![ksnip_20230519-105655](https://user-images.githubusercontent.com/6752679/239425383-e61e0f9b-8564-4526-aae2-a2e8b417cc41.png)

需要的是自动连排，每一行都手动修改数字和直接手动打1、2、3、没区别了

**Comment by Nriver** [comment]
改一次就行，后面就是连着的

**Comment by Suceru** [comment]
> 改一次就行，后面就是连着的
![image](https://github.com/Nriver/trilium-translation/assets/20983345/eb5bc01a-8e5b-4f1b-9e9c-ccf892eb35a7)
后面连着的4和5，然后中间插入一个空行，5就变为4了，这很不人性化

**Comment by Nriver** [comment]
这种功能逻辑的修改去问问上游ckeditor吧，我这里也不知道怎么改，只能告诉你怎么用的。
