### ISSUE TITLE
能不能更新一下docker汉化版的版本？

### ISSUE THREAD

**Issue by Lisland2032** [Nriver/trilium-translation#62]
docker汉化版最新只有0.57.5，为了同步，pc版也只能用这个版本？但旧版本任务管理功能没有啊
或者pc汉化版可以和docker原版同步吗？版本怎么对应？

**Comment by Nriver** [comment]
docker最新的是 0.60.1，你用了加速镜像吧，去掉加速镜像，用官方源。

这个问题在 [README](https://github.com/Nriver/trilium-translation/blob/main/README_CN.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E7%9A%84docker%E9%95%9C%E5%83%8F%E6%9B%B4%E6%96%B0%E4%B9%8B%E5%90%8E%E8%BF%98%E6%98%AF%E6%97%A7%E7%89%88%E7%9A%84) 里面有做解答

**Comment by Lisland2032** [comment]
我去掉加速镜像看了一下，最新还是只有0.59.4，网络不对吗？

**Comment by Nriver** [comment]
用latest，不要指定版本

**Comment by Lisland2032** [comment]
谢谢，已经更新成功。
另外请教一下，更新后数据大家一般是怎么恢复到新版本里面？数据库文件好吧没接口导入数据吧？导出成zip文件再导入到新版本？

**Comment by Nriver** [comment]
把数据目录映射出来就行了，参考我的docker-compose.yml文件，环境变量也要一起设置
