### ISSUE TITLE
笔记中上传大的附件后又删除，数据库的大小没有发生变化

### ISSUE THREAD

**Issue by Queqiongtao** [Nriver/trilium-translation#63]
我向笔记中上传了200M的附件，删除后，数据库的大小没有变化，如果是这样，这个数据库不是很容易变得非常大？数据备份已经关闭。

**Comment by Nriver** [comment]
左上 最近修改 永久删除已删除的笔记。
选项-高级 整理数据库。

**Comment by Queqiongtao** [comment]
可行  3Q.
