### ISSUE TITLE
是否可以出一个部署heroku的配置文件？

### ISSUE THREAD

**Issue by CosmoGao** [Nriver/trilium-translation#64]
原项目提供了一个部署到Heroku的脚本，不知道这个项目能否支持一下？
https://github.com/feilongfl/trilium-heroku

**Comment by Nriver** [comment]
我没用过heroku，看了一下最低5刀一个月？我用的racknerd一年才10刀。。。

**Comment by CosmoGao** [comment]
确实，之前heroku有免费的小时数，现在好像取消了

**Comment by Nriver** [comment]
我用的是racknerd，很便宜，最近又出了新的独立日促销。

可以参考这里
https://github.com/Nriver/trilium-translation/blob/main/README_CN.md#你用的是什么vps服务器跑的trilium-notes服务端
