### ISSUE TITLE
Linux服务端或者Docker镜像支持外部数据库么？最好是mysql

### ISSUE THREAD

**Issue by catalpatailscale** [Nriver/trilium-translation#65]
请问这个支持外部数据库么？Linux服务端或者Docker镜像都可以，最好是mysql，内部数据存储做异地备份比较麻烦，但如果用外部数据库集群的话就会简单恨过。如果支持的话请说明下如何配置，谢谢

**Comment by Nriver** [comment]
不支持。想异地备份，可以直接开个客户端同步。

**Comment by catalpatailscale** [comment]
好的，谢谢
