### ISSUE TITLE
0.60.4在windows11上打不开……但是英文版可以正常运行

### ISSUE THREAD

**Issue by hanson-reas** [Nriver/trilium-translation#68]
版本	Windows 11 家庭中文版 Insider Preview
版本	22H2
安装日期	‎2023/‎8/‎22
操作系统版本	23526.1000
序列号	5CD238F6YN
体验	Windows Feature Experience Pack 1000.23526.1000.0

**Comment by Nriver** [comment]
你运行了beta版的？数据库太新，把库删了再运行中文版

**Comment by hanson-reas** [comment]
> 你运行了beta版的？数据库太新，把库删了再运行中文版

厉害，把App Data里面的文件夹删了以后，一下子就解决了。

**Comment by gehaocool** [comment]
遇到了同样的问题，也是win11，先运行过英文版之后，中文版就无法打开
请问具体应该怎么删除数据库？

**Comment by Nriver** [comment]
> 遇到了同样的问题，也是win11，先运行过英文版之后，中文版就无法打开 请问具体应该怎么删除数据库？

建议把[常见问题](https://github.com/Nriver/trilium-translation/blob/main/README_CN.md#-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)看一遍
