### ISSUE TITLE
请问Linux服务器部署中文版的docker中，数据库备份文件可以用在英文版的trilium镜像恢复数据吗？

### ISSUE THREAD

**Issue by mffan0922** [Nriver/trilium-translation#69]
我看了所有的issue，没有找到如上问题的答案，辛苦帮忙看下，我的意思是，咱们这个中文版trilium镜像应用中的数据备份是否可以直接导入到英文版的docker中，其实我自己可以试一下的，今天太晚了准备明天试试，还是想发出来，也方便后来有相同疑问的老师查看。

如果可以的话，是那个`backup-daily.db`文件吗？

thinks！

![image](https://github.com/Nriver/trilium-translation/assets/63949101/861f5f5a-74ac-483b-9f2b-3204395ef7c9)

**Comment by Nriver** [comment]
只要版本号一致，中文和英文版的数据完全通用

**Comment by mffan0922** [comment]
> 只要版本号一致，中文和英文版的数据完全通用

OK, thx~
