### ISSUE TITLE
还会继续更新么？

### ISSUE THREAD

**Issue by longzekai** [Nriver/trilium-translation#7]

**Comment by Nriver** [comment]
会的。稳定的版本出来之后会更新，小版本看情况更新。之前有群友反馈自己跟着原版升级小版本遇到丢笔记的bug，我就没跟着原作者更新最新的了。以稳定为主，数据无价。

**Comment by wujita01** [comment]
从docker再到NRIVER的blog，再到github。宝藏大佬，谢谢您的分享。

**Comment by Nriver** [comment]
> 从docker再到NRIVER的blog，再到github。宝藏大佬，谢谢您的分享。

谢谢支持，不过我没有blog哦。
