### ISSUE TITLE
请考虑保留healthcheck

### ISSUE THREAD

**Issue by libook** [Nriver/trilium-translation#70]
原项目Dockerfile中提供了healthcheck https://github.com/zadam/trilium/blob/master/Dockerfile#L42
运行的这个脚本 https://github.com/zadam/trilium/blob/master/docker_healthcheck.js 实际上是向 /api/health-check 发送了请求，看是否正确返回。

**Comment by Nriver** [comment]
我重新打了一个镜像，重新拉一遍最新的镜像，然后参考最新的 https://github.com/Nriver/trilium-translation/blob/main/docker-compose.yml 把健康检查功能开启就行了
