### ISSUE TITLE
在docker compose中启用“健康检查”出问题

### ISSUE THREAD

**Issue by carcoonzyk** [Nriver/trilium-translation#71]
如题，命令行输入docker compose up返回错误：
yaml: line 15: did not find expected ',' or ']'
line 15:
`
healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/api/health-check | jq -e '.status == "ok"' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
`

**Comment by Nriver** [comment]
检查你的空格缩进是不是有问题

**Comment by carcoonzyk** [comment]
> 检查你的空格缩进是不是有问题
我只是将注释的符号‘#’ 去除变成：
`version: '3'
services:
  trilium-cn:
    image: nriver/trilium-cn
    restart: always
    ports:
      - "8090:8080"
    volumes:
      # 把同文件夹下的 trilium-data 目录映射到容器内
      - ./trilium-data:/root/trilium-data
    environment:
      # 环境变量表示容器内笔记数据的存储路径
      - TRILIUM_DATA_DIR=/root/trilium-data
    # 可选功能: 健康检查。需要启用的话，把下面的注释去掉
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/api/health-check | jq -e '.status == "ok"' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3`

**Comment by carcoonzyk** [comment]
> 检查你的空格缩进是不是有问题
已解决：
将原本docker-compose.yaml中
 `status == '”ok“`
把双引号改为单引号，即
`status == 'ok'`
得以通过
