### ISSUE TITLE
demo-cn导入覆盖问题？

### ISSUE THREAD

**Issue by hxchtiewei** [Nriver/trilium-translation#75]
您好，
我导入后发现并没有覆盖现有的“示例笔记”，发现是noteId不一致的原因。
我想把老的“示例笔记”删除，不过有“警告”。
![Snipaste_2023-11-08_13-57-49](https://github.com/Nriver/trilium-translation/assets/48231900/de9958ad-aae9-492d-9570-2bddaaf41a13)
已有一大堆笔记经深度关联了，我觉得这其实是trilium的很大的缺点。。。
版本更新时只更新主程序的吧？万一以后有新功能更新涉及这些模板变更，那岂不是要手工一个个更新？

**Comment by Nriver** [comment]
这个确实是要手动更新的，比如升级之后api变动，有些js需要手动修改一下，是避免不了的。

**Comment by hxchtiewei** [comment]
> 您好， 我导入后发现并没有覆盖现有的“示例笔记”，发现是noteId不一致的原因。 我想把老的“示例笔记”删除，不过有“警告”。 ![Snipaste_2023-11-08_13-57-49](https://user-images.githubusercontent.com/48231900/281277544-de9958ad-aae9-492d-9570-2bddaaf41a13.jpg) 已有一大堆笔记经深度关联了，我觉得这其实是trilium的很大的缺点。。。 版本更新时只更新主程序的吧？万一以后有新功能更新涉及这些模板变更，那岂不是要手工一个个更新？

貌似我搞错了，我还有另外一个叫“笔记”的笔记。。。这个截图关联的是“示例笔记”里的“笔记”。
请问老的“示例笔记“能否全部删除？有被引用吗？

**Comment by Nriver** [comment]
这个要看你有没有使用了，比如日记是不是还在里面。只要里面没有你写的笔记就可以删。

建议还是先备份一下数据库。

**Comment by hxchtiewei** [comment]
> 这个要看你有没有使用了，比如日记是不是还在里面。只要里面没有你写的笔记就可以删。
> 
> 建议还是先备份一下数据库。

好的，感谢回复~
