### ISSUE TITLE
mac版客户端下载打开还是英文版怎么回事

### ISSUE THREAD

**Issue by javahuitailang** [Nriver/trilium-translation#76]
在下载该版本之前下载了一个官方版的，然后打开软件发现没有中文，使用很不方便，于是找到了大佬的汉化版，下载对应的mac最新版打开，发现还是英文的，怎么解决

**Comment by Nriver** [comment]
删掉缓存。
建议把[常见问题](https://github.com/Nriver/trilium-translation/blob/main/README_CN.md#-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)先看一遍。
