### ISSUE TITLE
能否把canvas画布的手写体改为下图这样的，美观一些。

### ISSUE THREAD

**Issue by tiger7651** [Nriver/trilium-translation#77]
能否把canvas画布的手写体改为下图这样的，美观一些。字体我可以上传。

![image](https://github.com/Nriver/trilium-translation/assets/150779117/4f73d26f-261b-4fea-a9d7-1dbfd59d6cae)

**Comment by Nriver** [comment]
可以自己替换掉字体，然后自己编译一份
