### ISSUE TITLE
解压后打不开

### ISSUE THREAD

**Issue by leewwang** [Nriver/trilium-translation#79]
原trilium卸载干净后（无笔记数据），下载的trilium-translation，解压后打不开。windows，双击exe没反应，不知道啥情况。

**Comment by Nriver** [comment]
cmd运行看报错

**Comment by leewwang** [comment]
App db version is 227, while db version is 213. Migration needed.
ERROR: Direct migration from your current version is not supported. Please upgrade to the latest v0.60.X first and only then to this version.

好像是什么数据库版本问题，不清楚怎么处理。抱歉有点小白..

**Comment by Nriver** [comment]
你用了旧版的，要先升级到0.60.4在用新版的。或者直接删除旧的数据库，重新初始化。
