### ISSUE TITLE
没法打开程序

### ISSUE THREAD

**Issue by Orgin16** [Nriver/trilium-translation#8]
执行trilium.exe之后没有任何反应 但是能用trilium-portable.bat脚本打开

**Comment by Nriver** [comment]
可能是你用了高版本的trilium生成了数据库，低版本的trilium无法打开就退出了。使用命令行可以看到详细的错误信息。
我刚刚发了一个最新的汉化版，你可以试试。

**Comment by Orgin16** [comment]
新版本没这个问题了 感谢!
