### ISSUE TITLE
docker最新拉取运行报错

### ISSUE THREAD

**Issue by AoThen** [Nriver/trilium-translation#80]
./trilium.sh: line 2: ./node/bin/node: not found

版本latest，0.62.4
平台amd64
https://hub.docker.com/layers/nriver/trilium-cn/latest/images/sha256-46cade016e506f54829907fab5e3e12dae6909b1bfd185dc51207b027cd95c60?context=explore

**Comment by Nriver** [comment]
你这不是最新的，最新版已经不使用 trilium.sh 了，不可能出现这个报错

**Comment by Nriver** [comment]
看你发的链接的最后一行里面的内容，新版已经改成用 `node /app/arc/www` 启动了。

![ksnip_20231222-152352](https://github.com/Nriver/trilium-translation/assets/6752679/c02afb92-b851-4bf2-b3a1-97dce80a9f4e)

我本地运行amd64没有问题的。

**Comment by AoThen** [comment]
我的问题，sorry，不好意思啊，我重新检查发现没有带latest，也就是我之前直接拉的是nriver/trilium-cn，笔记好像没有出现兼容问题，不知道是拉了哪个版本的，sha256:f94bb494dbbc0f761912a3f4d36b4b99383cff4da05414e62a91bc1851dc79d9
