### ISSUE TITLE
突然卡死了

### ISSUE THREAD

**Issue by leewwang** [Nriver/trilium-translation#81]
在记笔记过程中，突然卡死。
试了几种方法还是不行——
1、重启软件；
2、全盘杀毒；
3、升级windows系统，重启电脑；
4、管理员身份运行；
5、卸载后重装（最新的两版都试了）；

目前还是不行，一直卡着不动，只能打开和关闭软件界面。其他都操作不了。想问下，有什么解决办法吗？麻烦了！

**Comment by leewwang** [comment]
再一次清理卸载重装后，软件启动正常了。不过原先的笔记都没了，我把之前复制的db文件覆盖到C盘的备份文件夹里，再打开恢复了原先笔记，不过笔记恢复了，软件又老样子卡着动不了。。不知道哪里出了问题

**Comment by 9chico** [comment]
为什么只有快捷键那里显示中文啊，其他还是英文

**Comment by Nriver** [comment]
> 再一次清理卸载重装后，软件启动正常了。不过原先的笔记都没了，我把之前复制的db文件覆盖到C盘的备份文件夹里，再打开恢复了原先笔记，不过笔记恢复了，软件又老样子卡着动不了。。不知道哪里出了问题

cmd里运行，看报什么错

**Comment by Nriver** [comment]
> 为什么只有快捷键那里显示中文啊，其他还是英文

删除缓存喝数据块，参考readme里的常见问题

**Comment by leewwang** [comment]
> > 再一次清理卸载重装后，软件启动正常了。不过原先的笔记都没了，我把之前复制的db文件覆盖到C盘的备份文件夹里，再打开恢复了原先笔记，不过笔记恢复了，软件又老样子卡着动不了。。不知道哪里出了问题
> 
> cmd里运行，看报什么错

没显示有什么报错。“All consistency checks passed with no errors detected”

**Comment by leewwang** [comment]
下载安装了原版trilium后也是一样，只要把db文件覆盖粘贴到C盘的trilium-data文件夹里就打开卡死，停留在刚出现卡住时的笔记页面。
![Snipaste_2024-01-01_19-38-53](https://github.com/Nriver/trilium-translation/assets/64349788/5d8c5103-8cdb-4d29-b6b9-74a93320874a)

**Comment by Nriver** [comment]
--disable-gpu 也不行吗？那我就不知道了。

**Comment by Nriver** [comment]
后续有问题请反馈到 https://github.com/zadam/trilium/issues/3869
