### ISSUE TITLE
yml启动失败

### ISSUE THREAD

**Issue by leap233** [Nriver/trilium-translation#82]
这是我的 docker-compose.yml 文件(没有做任何修改):
version: '3'
services:
  trilium-cn:
    image: nriver/trilium-cn
    restart: always
    ports:
      - "8080:8080"
    volumes:
      # 把同文件夹下的 trilium-data 目录映射到容器内
      - ./trilium-data:/root/trilium-data
    environment:
      # 环境变量表示容器内笔记数据的存储路径
      - TRILIUM_DATA_DIR=/root/trilium-data
    # 可选功能: 健康检查。需要启用的话，把下面的注释去掉
    #healthcheck:
    #  test: ["CMD-SHELL", "curl --fail http://localhost:8080/api/health-check | jq -e '.status == "ok"' || exit 1"]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3

执行:
$ docker-compose up -d

发生以下错误:
Pulling trilium-cn (nriver/trilium-cn:)...
latest: Pulling from nriver/trilium-cn
c926b61bad3b: Pull complete
3ebae63ae1d8: Pull complete
4df6e7e40a3f: Pull complete
bd5b864d1249: Pull complete
a33f547192f2: Pull complete
4f4fb700ef54: Pull complete
6f3aa6a3e507: Pull complete
Digest: sha256:2426d058f0ee7c0525e30b06ecdfe925529e8be4fa3d37fef214c69c6db75ef1
Status: Downloaded newer image for nriver/trilium-cn:latest
Creating _trilium-cn_1 ... error

ERROR: for _trilium-cn_1  Cannot create container for service trilium-cn: Invalid container name (_trilium-cn_1), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

ERROR: for trilium-cn  Cannot create container for service trilium-cn: Invalid container name (_trilium-cn_1), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
ERROR: Encountered errors while bringing up the project.

docker版本:
Docker version 24.0.7, build afdd53b

**Comment by Nriver** [comment]
我这里没有问题哦
![ksnip_20240103-111729](https://github.com/Nriver/trilium-translation/assets/6752679/5db84c9f-870f-4909-8612-3fb8abaa93ad)

你用的是widnows吗？

**Comment by leap233** [comment]
> 我这里没有问题哦 ![ksnip_20240103-111729](https://private-user-images.githubusercontent.com/6752679/293826980-5db84c9f-870f-4909-8612-3fb8abaa93ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNTIzNzMsIm5iZiI6MTcwNDI1MjA3MywicGF0aCI6Ii82NzUyNjc5LzI5MzgyNjk4MC01ZGI4NGM5Zi04NzBmLTQ5MDktODYxMi0zZmI4YWJhYTkzYWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDNUMDMyMTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTc4NzUxMDZiMjhiODM3MTEzMjNjNjIzY2ExMzViZTE2ZGVmNTRkZjhhZGFkY2U4ZWQ5NTI2Y2UxMzcyYjkxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.J6_KatyQ1B0df2VlKcz82gz0MrCSgJ8UW58H9PgwOpA)
> 
> 你用的是widnows吗？


系统是ubuntu20.04

**Comment by Nriver** [comment]
docker-compose 版本是不是没更新？

**Comment by leap233** [comment]
> docker-compose 版本是不是没更新？

好像是的 我的  docker-compose  版本是1.29, 我要更新到3版本以上嘛

**Comment by Nriver** [comment]
我用的是 2.23.3，升级一下吧

**Comment by leap233** [comment]
> 
好的 谢谢
