### ISSUE TITLE
AUR包是否应当改名为trilium-cn-bin？

### ISSUE THREAD

**Issue by renyuneyun** [Nriver/trilium-translation#83]
今天在排查trilium的bug时发现了这个翻译项目，于是顺手试了一下。
在深入检查时，发现AUR包是一个binary包，而非从源代码编译的。如果我没弄错的话，对于二进制包（即直接使用编译好的程序而非下载源代码再编译），习惯上命名中要加上`-bin`，比如`trilium-cn-bin`。

顺便感谢文档，总算看到一个介绍如何（从源代码）打包trilium的说明了 ;p

**Comment by Nriver** [comment]
感谢提醒，新开了 `trilium-cn-bin` 和 `trilium-server-cn-bin`
