### ISSUE TITLE
中文月份排序优化

### ISSUE THREAD

**Issue by X-Bruce-Y** [Nriver/trilium-translation#86]
大佬好，感谢你的工作，trilium中文版已完全取代了我使用了许久的onenote。
想知道是否有可能解决中文月份排序问题，例如目前用#sorted排序结果为“一月/三月/二月”，用#sorted #sortNatural排序结果为“二月/三月/一月”，其它内置的sort标签结果与#sorted相同。
这个在日记功能中尤为重要，月份被打乱看起来太不舒服了。如果还能添加逆序功能就能好了。

再次感谢！

**Comment by Nriver** [comment]
`#sortNatural` 自然排序是按拼音字母顺序的。

日记每天使用的时候它会自动按照正常的顺序排列的，没必要手动添加 `#sorted` 干预。

逆向排序是 `#sortDirection=DESC `。

**Comment by X-Bruce-Y** [comment]
![MonthOrderProblem](https://github.com/Nriver/trilium-translation/assets/12207447/e1972929-a00c-4ca5-a09e-e7a6f7add6f7)
你好，我这边sorted无法正确排序中文月份，请问是哪里的设置有问题吗？

**Comment by X-Bruce-Y** [comment]
> `#sortNatural` 自然排序是按拼音字母顺序的。
> 
> 日记每天使用的时候它会自动按照正常的顺序排列的，没必要手动添加 `#sorted` 干预。
> 
> 逆向排序是 `#sortDirection=DESC `。

![Uploading MonthOrderProblem.png…]()
你好，我这边sorted无法正确排序中文月份，请问是哪里的设置有问题吗？

**Comment by X-Bruce-Y** [comment]
> `#sortNatural` 自然排序是按拼音字母顺序的。
> 
> 日记每天使用的时候它会自动按照正常的顺序排列的，没必要手动添加 `#sorted` 干预。
> 
> 逆向排序是 `#sortDirection=DESC `。

![MonthOrderProblem](https://github.com/Nriver/trilium-translation/assets/12207447/428ba4c3-1700-408d-a15c-7806b9fc956c)

你好，我这边sorted无法正确排序中文月份，请问是哪里的设置有问题吗？

**Comment by Nriver** [comment]
排序就是无法按照中文数字排序的。

默认的日记格式应该是这样的月份，前面有数字
![ksnip_20240221-174402](https://github.com/Nriver/trilium-translation/assets/6752679/229e4110-b59c-4b77-b59f-edc79b96a193)

**Comment by X-Bruce-Y** [comment]
> 排序就是无法按照中文数字排序的。
> 
> 默认的日记格式应该是这样的月份，前面有数字 ![ksnip_20240221-174402](https://private-user-images.githubusercontent.com/6752679/306574503-229e4110-b59c-4b77-b59f-edc79b96a193.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1Nzk2NTUsIm5iZiI6MTcwODU3OTM1NSwicGF0aCI6Ii82NzUyNjc5LzMwNjU3NDUwMy0yMjllNDExMC1iNTljLTRiNzctYjU5Zi1lZGM3OWI5NmExOTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMDUyMjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzY2NjM4OTFlYTI2MTQxMWI3ZjcxMTI4NmQzZTMzOWRhMGE5MTJlZGVhMWYzODQ1N2U5YmQzMzgzMjBkOWM4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.27aeXZ1pUkrtSPIYy9nmvHMdhDZSSyXxdOW0hrE3kOc)

了解了，感谢！
