### ISSUE TITLE
求教如何编译apple m1 arm64 版本。

### ISSUE THREAD

**Issue by jinxiaoman** [Nriver/trilium-translation#87]
x64 可以用，但是偶然推出后再次打开就白屏，必须重启电脑才ok。看任务，相关的都已经关闭干净了。很疑惑，想尝试编译arm64

**Comment by Nriver** [comment]
不好意思，我没有苹果电脑，不清楚m1有什么特殊的地方。

不过我写过一个在安卓手机上编译源码运行的教程，你可以参考一下，思路应该是差不多的。 https://github.com/zadam/trilium/discussions/4542
