### ISSUE TITLE
maybe it is a problem?

### ISSUE THREAD

**Issue by carcoonzyk** [Nriver/trilium-translation#88]
docker版里[0.62.4]包括最新的镜像，在插入或拖入图片时无法像之前的版本一样保持“项目符号列表”的排序，而是自成一行。不仅如此，它还破坏之后“项目符号列表”的从属关系。目前已退回0.61.15版本，希望有什么好的解决方法？

**Comment by Nriver** [comment]
这个可能和ckeditor有关，之前有个版本的ckeditor升级之后多了一些功能，但是引入了一些bug，所以后来作者又给降级回去了，就少了一些功能。

目前暂时只能等ckeditor修复bug之后再等trilium这边更新了。

**Comment by carcoonzyk** [comment]
好的
