### ISSUE TITLE
大佬，请教如何设置，可以打开一个新标签页，期望是点击某个笔记，例如notes显示新建标签页。这个页面可以通过renderNote设置出来吗？

### ISSUE THREAD

**Issue by jinxiaoman** [Nriver/trilium-translation#89]
发现这个新建标签页对于多个 wordspace 很好用。
<img width="1399" alt="image" src="https://github.com/Nriver/trilium-translation/assets/30037936/d5b25683-c8c8-437e-87ef-9059361b502e">

**Comment by Nriver** [comment]
没太看懂，你是想要 `Ctrl+T` 吗？
