### ISSUE TITLE
感觉这个笔记的搜索功能不太好，不能直接显示出相关的文本内容，是我用法不对吗？

### ISSUE THREAD

**Issue by wuyigui323** [Nriver/trilium-translation#9]
比如我搜索一个词，只能显示标题，我要点进标题去肉眼从头到尾找关键词，也没有自动高亮显示关键词

**Comment by Nriver** [comment]
快速搜索（ctrl+s）点击在搜索中显示，或者点左上的放大镜搜索。
每个搜索结果条目可以点左侧的 > 打开来看。
需要高亮的话在搜索结果里再次按ctrl+f搜索。
