### ISSUE TITLE
docker compose部署支持修改成https吗

### ISSUE THREAD

**Issue by yanchao963852741** [Nriver/trilium-translation#92]
大佬帮忙看下，使用http时正常访问，证书拷贝到了trilium-data目录下，config.ini里面改了https和设置了证书，改完之后访问https+8080端口提示此站点的连接不安全，发送了无效响应，日志中也没有报错
09:13:55.594 DB size: 3735 KB
09:14:02.489 {
  "appVersion": "0.62.6",
  "dbVersion": 227,
  "syncVersion": 31,
  "buildDate": "2024-01-21T23:49:23+01:00",
  "buildRevision": "4f8073daa7cff1b8b6737ae45792b2e87c2adf33",
  "dataDirectory": "/root/trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2024-03-11T09:13:53.552Z"
}
09:14:02.490 CPU model: Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, logical cores: 1 freq: 2593 Mhz
09:14:02.492 Trusted reverse proxy: false
09:14:03.350 App HTTPS server starting up at port 8080
09:14:03.362 Listening on port 8080
09:14:03.397 Becca (note cache) load took 32ms
09:14:07.410 Table counts: notes: 384, revisions: 9, attachments: 36, branches: 392, attributes: 655, etapi_tokens: 0, blobs: 233
09:14:07.441 All consistency checks passed with no errors detected (took 33ms)
10:14:02.862 Optimizing database
10:14:02.864 Optimization finished in 1ms.
10:14:02.899 Table counts: notes: 384, revisions: 9, attachments: 36, branches: 392, attributes: 655, etapi_tokens: 0, blobs: 233
10:14:02.926 All consistency checks passed with no errors detected (took 28ms)
11:14:03.191 Table counts: notes: 384, revisions: 9, attachments: 36, branches: 392, attributes: 655, etapi_tokens: 0, blobs: 233
11:14:03.218 All consistency checks passed with no errors detected (took 28ms)
12:14:02.760 Table counts: notes: 384, revisions: 9, attachments: 36, branches: 392, attributes: 655, etapi_tokens: 0, blobs: 233
12:14:02.788 All consistency checks passed with no errors detected (took 28ms)

**Comment by Nriver** [comment]
这个我也不知道，https还是在nginx里面配置比较方便管理。

**Comment by yanchao963852741** [comment]
大佬，那centos可以部署到本地吗，看文档里面两种方式一种是docker一种是aur的，centos是不是只能编译部署

**Comment by Nriver** [comment]
直接运行linux server版的试试，不过centos太老了，建议换个新的系统
