### ISSUE TITLE
添加字体

### ISSUE THREAD

**Issue by 2576168920** [Nriver/trilium-translation#93]
今天刚用，不大熟悉，见谅
我在记录时，写下 O和0，字符O和数字0，难以区分，建议增加Consolas(代码使用较为友好)等字体，搜了下，对于使用者大概是要挂载/usr/share/fonts目录，由于对docker不熟悉，不知道docker run参数，不敢瞎折腾

**Comment by Nriver** [comment]
不支持使用系统字体
