### ISSUE TITLE
您好，我想请教一下在不应用纯文本的情况下取消段落缩进操作呀，只要回车就自动缩进了，然后如果想缩进只能跑到上一行末尾...

### ISSUE THREAD

**Issue by JdiLfc** [Nriver/trilium-translation#94]

**Comment by Nriver** [comment]
没看懂，请截图

**Comment by JdiLfc** [comment]
![image](https://github.com/Nriver/trilium-translation/assets/74535526/52abdf85-05e5-4623-becc-ab96cb896e0e)
就是这个首行缩进

**Comment by JdiLfc** [comment]
能不能取消这个缩进呀

**Comment by Nriver** [comment]
你用了什么第三方的主题或者样式吗？

默认是顶格的
![ksnip_20240401-110456](https://github.com/Nriver/trilium-translation/assets/6752679/a62a9b64-3368-4d24-ac10-07693197c9f7)

**Comment by JdiLfc** [comment]
谢谢您，主题的原因
