### ISSUE TITLE
从服务器同步遇到问题

### ISSUE THREAD

**Issue by TengJW** [Nriver/trilium-translation#97]
从已有服务器同步，密码已经输入了，却提示密码不能为空
<img width="1164" alt="image" src="https://github.com/Nriver/trilium-translation/assets/22724544/42190bd8-138f-4bd6-bc69-e9283f30fe40">

**Comment by Nriver** [comment]
没有遇到过，看看控制台和网络的请求有什么报错信息

**Comment by TengJW** [comment]
发现原因了，edge浏览器不兼容，用Safari浏览器就行了
