### ISSUE TITLE
关于更新软件后的数据转移

### ISSUE THREAD

**Issue by Userwei0418** [Nriver/trilium-translation#99]
如果之前用了旧版本 现在想更新到新版本 但原本数据很大有5g 该怎么快速转移呢 直接拖db文件打不开新版软件 用一个一个笔记导出导入又过于麻烦

**Comment by Nriver** [comment]
命令行里启动程序看报错，很久每更新的话，一般是要先升级到某个版本才能往上升，报错信息里会有提示。
